name: continuous-integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  linkcheck:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -rrequirements.txt
    - name: Run linkcheck
      run: sphinx-build -b linkcheck docs/ docs/_build/linkcheck
